ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    host: localhost
    port: 1414
    user: admin
    password: passw0rd
    queues:
      - DEV.QUEUE.1
      - DEV.QUEUE.2
      - DEV.QUEUE.3
#    backout-threshold: 1
#    backout-requeue-queue: MY.DEAD.LETTER.QUEUE
